using SQLite;
using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using Xamarin.Forms;
using Xamarin.Forms.Xaml;

namespace YourFoodApp3
{
    public partial class App : Application
    {
        private static Database database;

        public static List<PreloadedRecipe> preloadedRecipe { get; set; }

        public static Database Database
        {
            get
            {
                //create database in phone
                if (database == null)
                {
                    database = new Database(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "yourfood.db3"));
                }
                return database;
            }
        }
        public App()
        {
            InitializeComponent();

            //insert preloaded recipes into preloadedrecipe table - do it once only          

            //preloadedRecipe = new List<PreloadedRecipe>();

            //preloadedRecipe.Add(new PreloadedRecipe { Id = 1, RecipeName = "Mushroom & Tofu Stir-Fry", Description = "Quick and easy, making it a great go-to weeknight meal.", Time = "20 mins", Ingredients = "\u2022 1 bunch scallions, trimmed and cut into 2-inch pieces\r\n\r\n\u2022 1 tablespoon grated fresh ginger\r\n\r\n\u2022 1 large clove garlic, grated\r\n\r\n\u2022 1 (8 ounce) container baked tofu or smoked tofu, diced\r\n\r\n\u2022 3 tablespoons oyster sauce or vegetarian oyster sauce", Steps = "1) Heat 2 tablespoons oil in a large flat-bottom wok or cast-iron skillet over high heat.\r\n\r\n2) Add mushrooms and bell pepper; cook, stirring occasionally, until soft, about 4 minutes.\r\n\r\n3) Stir in scallions, ginger and garlic; cook for 30 seconds more.\r\n\r\n4) Transfer the vegetables to a bowl.", Bookmark = "No", Image = "tofu.png" });
            //preloadedRecipe.Add(new PreloadedRecipe { Id = 2, RecipeName = "Balsamic-Parmesan Sautéed Spinach", Description = "Quick and flavorful side dish.", Time = "15 mins", Ingredients = "• 2 tablespoons extra-virgin olive oil\r\n\r\n• 3 cloves garlic, minced\r\n\r\n• 1 pound fresh spinach\r\n\r\n• ¼ teaspoon salt\r\n\r\n• ¼ teaspoon ground pepper\r\n\r\n• 2 tablespoons grated Parmesan cheese\r\n\r\n• 4 teaspoons good-quality balsamic vinegar or balsamic glaze", Steps = "1) Heat oil in a large pot over medium heat.\r\n\r\n2) Add garlic and cook, stirring, until fragrant, 30 seconds to 1 minute.\r\n\r\n3) Add spinach, salt and pepper; toss to coat.\r\n\r\n4) Cook, stirring, until just wilted, 3 to 5 minutes.\r\n\r\n5) Remove from heat and stir in Parmesan.\r\n\r\n6) Drizzle with vinegar.", Bookmark = "No", Image = "spinach.png" });
            //preloadedRecipe.Add(new PreloadedRecipe { Id = 3, RecipeName = "Skillet Steak with Mushroom Sauce", Description = "Steak, broccolini and pea dinner is a one-skillet meal", Time = "25 mins", Ingredients = "• 12 ounces boneless beef top sirloin steak, cut 1 inch thick and trimmed\r\n\r\n• 2 teaspoons salt-free steak grilling seasoning.\r\n\r\n• 2 cloves garlic, minced\r\n\r\n• ½ teaspoon salt, divided\r\n\r\n• 2 teaspoons canola oil\r\n\r\n• 6 ounces broccolini, trimmed\r\n\r\n• 2 cups frozen peas\r\n\r\n• 1 teaspoon chopped fresh thyme\r\n\r\n3 cups sliced fresh mushrooms\r\n\r\n1 cup unsalted beef broth\r\n\r\n1 tablespoon whole-grain mustard\r\n\r\n• 2 teaspoons cornstarch", Steps = "1) Preheat oven to 350°F.\r\n\r\n2) Sprinkle steak with steak seasoning, garlic and 1/4 teaspoon salt.\r\n\r\n3) Heat oil in a 12-inch cast-iron skillet over medium-high heat.\r\n\r\n4) Add the steak and broccolini. Cook for 4 minutes, turning the broccolini once (do not turn the steak).\r\n\r\n5) Place peas around the steak; sprinkle with thyme.\r\n\r\n6) Transfer the skillet to oven and bake until the steak is medium-rare (145°F), about 8 minutes.\r\n\r\n7) Transfer the steak and vegetables to a plate (leave the drippings in the pan); cover and keep warm.\r\n\r\n8) Add mushrooms to the drippings in the pan.\r\n\r\n9) Cook over medium-high heat for 3 minutes, stirring occasionally.\r\n\r\n10) Whisk broth, mustard, cornstarch and the remaining ¼ teaspoon salt in a small bowl or measuring cup; add to the pan with the mushrooms.\r\n\r\n11) Cook, stirring, until thick and bubbly, about 1 to 2 minutes.\r\n\r\n12) Cook, stirring, for 1 minute more.\r\n\r\n13) Serve the steak and vegetables with the sauce.", Bookmark = "No", Image = "skillet.png" });
            //preloadedRecipe.Add(new PreloadedRecipe { Id = 4, RecipeName = "Eggplant & Chickpea Baked Pasta", Description = "Comforting vegetarian baked-pasta dish.", Time = "50 mins", Ingredients = "• 8 ounces whole-wheat fusilli\r\n\r\n• ½ cup coarse dry whole-wheat breadcrumbs (see Note)\r\n\r\n• 1 tablespoon extra-virgin olive oil\r\n\r\n• 3 cup Eggplant & Chickpea Stew (see associated recipe)\r\n\r\n• 1 cup crumbled feta cheese\r\n\r\n• ½ cup chopped fresh mint or basil, divided\r\n\r\n• 2 tablespoons lemon juice", Steps = "1) Preheat oven to 350 degrees F.\r\n\r\n2) Coat an 8-inch-square (or similar 2-quart) baking dish with cooking spray.\r\n\r\n3) Bring a large pot of water to a boil.\r\n\r\n4) Cook pasta according to package directions. Drain and rinse.\r\n\r\n5) Combine breadcrumbs and oil in a small bowl.\r\n\r\n6) Toss the pasta with stew, feta, 1/4 cup mint (or basil) and lemon juice in a large bowl.\r\n\r\n7) Spread the mixture in the prepared baking dish. Top with the breadcrumb mixture.\r\n\r\n8) Bake until the topping is golden and crispy, about 30 minutes.\r\n\r\n9) Sprinkle with the remaining 1/4 cup mint (or basil). ", Bookmark = "No", Image = "eggplant.png" });
            //preloadedRecipe.Add(new PreloadedRecipe { Id = 5, RecipeName = "Sheet-Pan Steak & Potatoes", Description = "Easy and healthy—take on steak frites.", Time = "35 mins", Ingredients = "• 1 pound potatoes, cut into 1/2-inch wedges\r\n\r\n• 2 tablespoons extra-virgin olive oil, divided\r\n\r\n• ¾ teaspoon salt, divided\r\n\r\n• ¾ teaspoon ground pepper, divided\r\n\r\n• 4 cups chopped asparagus\r\n\r\n• 1 ¼ pounds skirt steak, trimmed\r\n\r\n• ½ teaspoon garlic powder\r\n\r\n• ½ teaspoon dried rosemary\r\n\r\n• 3 tablespoons crumbled blue cheese", Steps = "1) Preheat oven to 425 degrees F.\r\n\r\n2) Toss potatoes with 1 tablespoon oil and 1/4 teaspoon each salt and pepper in a large bowl. Spread evenly on a rimmed baking sheet. Roast for 15 minutes.\r\n\r\n3) Toss asparagus with the remaining 1 tablespoon oil and 1/4 teaspoon each salt and pepper in the bowl. Stir into the potatoes on the baking sheet.\r\n\r\n4) Sprinkle steak with garlic powder, rosemary and the remaining 1/4 teaspoon each salt and pepper.\r\n\r\n5) Roast until the steak is cooked and the vegetables are tender, 10 to 15 minutes more.\r\n\r\n6) Transfer the steak to a serving platter.\r\n\r\n7) Stir blue cheese into the vegetables and serve with the steak.", Bookmark = "No", Image = "pansteak.png" });
            //preloadedRecipe.Add(new PreloadedRecipe { Id = 6, RecipeName = "Kale & Quinoa Salad with Lemon Dressing", Description = "Kale-quinoa salad pops with different flavors and textures", Time = "25 mins", Ingredients = "• 1 bunch lacinato kale, stemmed and chopped\r\n\r\n• 6 tablespoons extra-virgin olive oil\r\n\r\n• 3 tablespoons lemon juice\r\n\r\n• 2 tablespoons chopped shallot\r\n\r\n• 1 teaspoon honey\r\n\r\n• ½ teaspoon salt\r\n\r\n• ¼ teaspoon ground pepper\r\n\r\n• 2 cups grape or cherry tomatoes, halved\r\n\r\n• 2 cups cooked quinoa\r\n\r\n• 1 English cucumber, thinly sliced\r\n\r\n• 1 medium red bell pepper, sliced\r\n\r\n• 1 medium yellow bell pepper, sliced\r\n\r\n• 1 (15 ounce) can unsalted chickpeas, rinsed\r\n\r\n• ¾ cup feta cheese, crumbled\r\n\r\n• ½ cup sliced almonds, toasted", Steps = "1) Place kale in a large serving bowl. Whisk together oil, lemon juice, shallot, honey, salt and pepper in a small bowl.\r\n\r\n2) Pour 2 to 3 tablespoons of the dressing over the kale; lightly massage until slightly wilted, 1 to 2 minutes.\r\n\r\n3) Top the kale with tomatoes, quinoa, cucumber, peppers, chickpeas, feta and almonds.\r\n\r\n4) Drizzle with the remaining dressing and toss before serving.", Bookmark = "No", Image = "kale.png" });
            //preloadedRecipe.Add(new PreloadedRecipe { Id = 7, RecipeName = "Lentil & Goat Cheese Toast", Description = "Simple goat cheese toast", Time = "10 mins", Ingredients = "• 2 tablespoons goat cheese\r\n\r\n• 2 slices olive sourdough bread, toasted\r\n\r\n• ⅔ cup rinsed canned French green lentils\r\n\r\n• 2 tablespoons chopped walnuts, toasted", Steps = "1) Spread 1 tablespoon goat cheese on each slice of toast. Top each with 1/3 cup lentils and 1 tablespoon walnuts.", Bookmark = "No", Image = "goatcheese.png" });
            //preloadedRecipe.Add(new PreloadedRecipe { Id = 8, RecipeName = "Pan-Seared Steak with Crispy Herbs & Escarole", Description = "Healthy dinner and quick to prepare.", Time = "20 mins", Ingredients = "• 1 pound sirloin steak, about 1/2 inch thick\r\n\r\n• ½ teaspoon salt, divided\r\n\r\n• ½ teaspoon ground pepper, divided\r\n\r\n• 2 tablespoons grapeseed oil or canola oil\r\n\r\n• 4 cloves garlic, crushed\r\n\r\n• 5 sprigs fresh thyme\r\n\r\n• 3 sprigs fresh sage\r\n\r\n• 1 sprig fresh rosemary\r\n\r\n• 16 cups chopped escarole", Steps = "1) Sprinkle steak with 1/4 teaspoon each salt and pepper.\r\n\r\n2) Heat a large cast-iron skillet over medium-high heat.\r\n\r\n3) Add the steak and cook until charred on one side, about 3 minutes.\r\n\r\n4) Turn the steak over and add oil, garlic, thyme, sage and rosemary.\r\n\r\n5) Cook, stirring the herbs occasionally, until an instant-read thermometer inserted in the thickest part of the steak reaches 125 degrees F for medium-rare, 3 to 4 minutes.\r\n\r\n6) Transfer the steak to a plate and top with the garlic and herbs.\r\n\r\n7) Tent with foil.\r\n\r\n8) Add escarole and the remaining 1/4 teaspoon each salt and pepper to the pan.\r\n\r\n9) Cook, stirring often, until the escarole starts to wilt, about 2 minutes.", Bookmark = "No", Image = "steakescarole.png" });
            //preloadedRecipe.Add(new PreloadedRecipe { Id = 9, RecipeName = "Chickpea Tuna Salad", Description = "Perfect lunch to pack for work or school.", Time = "20 mins", Ingredients = "• 2 tablespoons lemon juice\r\n\r\n• 1 tablespoon nonpareil capers, rinsed and chopped\r\n\r\n• 1 tablespoon finely chopped shallot\r\n\r\n• ¼ teaspoon salt\r\n\r\n• ¼ teaspoon ground pepper\r\n\r\n• 1 (15 ounce) can no-salt-added chickpeas, rinsed\r\n\r\n• 1 (6.7 ounce) jar oil-packed tuna, drained\r\n\r\n• 1 cup halved cherry tomatoes\r\n\r\n• 1 cup thinly sliced English cucumber\r\n\r\n• ½ cup crumbled feta cheese\r\n\r\n• 2 tablespoons chopped fresh dill\r\n\r\n• 3 tablespoons extra-virgin olive oil\r\n\r\n• 3 cups baby spinach", Steps = "1) Stir lemon juice, capers, shallot, salt and pepper together in a large bowl. Let stand for 5 minutes.\r\n\r\n2) Meanwhile, toss chickpeas, tuna, tomatoes, cucumber, feta and dill together in a large bowl.\r\n\r\n3) Whisk oil into the lemon juice mixture until fully incorporated. Spoon about 5 tablespoons of the dressing into the chickpea mixture; toss to coat.\r\n\r\n4) Add spinach to the remaining dressing in the large bowl; toss to coat.\r\n\r\n5) Divide the spinach evenly among 4 plates; top each plate with 1 1/4 cups chickpea mixture. Serve immediately.", Bookmark = "No", Image = "chickpea.png" });
            //preloadedRecipe.Add(new PreloadedRecipe { Id = 10, RecipeName = "Chickpea Fritters", Description = "Crispy exterior with a light and fluffy center flavored with fresh chopped herbs.", Time = "30 mins", Ingredients = "• ½ cup plain low-fat Greek yogurt\r\n\r\n• ¼ cup crumbled feta cheese\r\n\r\n• 1 tablespoon lemon juice\r\n\r\n• ¼ teaspoon honey\r\n\r\n• 1 tablespoon chopped fresh dill, divided, plus more for garnish\r\n\r\n• 1 tablespoon thinly sliced chives, divided, plus more for garnish\r\n\r\n• 2 teaspoons finely chopped garlic, divided\r\n\r\n• 1 (15 ounce) can unsalted chickpeas, rinsed\r\n\r\n• ⅓ cup chickpea flour\r\n\r\n• 1 tablespoon tahini\r\n\r\n• ½ teaspoon ground cumin\r\n\r\n• ½ teaspoon ground coriander\r\n\r\n• 1 large egg, lightly beaten\r\n\r\n• ½ teaspoon salt\r\n\r\n• 3 tablespoons canola oil", Steps = "1) Combine yogurt, feta, lemon juice, honey and 1 teaspoon each dill, chives and garlic in a medium bowl; stir until blended. Refrigerate until ready to serve.\r\n\r\n2) Place chickpeas in a large bowl and mash with the back of a fork or a potato masher until almost smooth but some chunks remain.\r\n\r\n3) Add chickpea flour, tahini, cumin, coriander, egg, salt and the remaining 2 teaspoons each dill and chives and 1 teaspoon garlic; stir until combined.\r\n\r\n4) Heat 1 1/2 tablespoons oil in a large nonstick skillet over medium-high heat. Working with half of the chickpea mixture at a time, scoop even tablespoonfuls into the hot skillet.\r\n\r\n5) Use the back of a spoon dipped in water to press down slightly to flatten into about 2-inch-diameter cakes.\r\n\r\n6) Cook, turning once, until golden brown on both sides, about 1 to 2 minutes per side.\r\n\r\n7) Serve with the yogurt-feta dip", Bookmark = "No", Image = "fritters.png" });
            //preloadedRecipe.Add(new PreloadedRecipe { Id = 11, RecipeName = "White Bean & Sun-Dried Tomato Gnocchi", Description = "This dish a great source of vitamins C and K.", Time = "20 mins", Ingredients = "• ½ cup sliced oil-packed sun-dried tomatoes plus 2 tablespoons oil from the jar, divided\r\n\r\n• 1 (16 ounce) package shelf-stable gnocchi\r\n\r\n• 1 (15 ounce) can low-sodium cannellini beans, rinsed\r\n\r\n• 1 (5 ounce) package baby spinach\r\n\r\n• 1 large shallot, minced\r\n\r\n• ⅓ cup low-sodium no-chicken broth or chicken broth\r\n\r\n• ⅓ cup heavy cream\r\n\r\n• 1 tablespoon lemon juice\r\n\r\n• ¼ teaspoon salt\r\n\r\n• ¼ teaspoon ground pepper\r\n\r\n• 3 tablespoons fresh basil leaves", Steps = "1) Heat 1 tablespoon oil in a large nonstick skillet over medium-high heat.\r\n\r\n2) Add gnocchi and cook, stirring often, until plumped and starting to brown, about 5 minutes.\r\n\r\n3) Add beans and spinach and cook until the spinach is wilted, about 1 minute.\r\n\r\n4) Transfer to a plate.\r\n\r\n5) Add the remaining 1 tablespoon oil to the pan and heat over medium heat.\r\n\r\n6) Add sun-dried tomatoes and shallot; cook, stirring, for 1 minute.\r\n\r\n7) Increase heat to high and add broth. Cook until the liquid has mostly evaporated, about 2 minutes.\r\n\r\n8) Reduce heat to medium and stir in cream, lemon juice, salt and pepper.\r\n\r\n9) Return the gnocchi mixture to the pan and stir to coat with the sauce.\r\n\r\n10) Serve topped with basil.", Bookmark = "No", Image = "gnocchi.png" });
            //preloadedRecipe.Add(new PreloadedRecipe { Id = 12, RecipeName = "Beef Tacos", Description = "Suitable for your taco night.", Time = "30 mins", Ingredients = "• 24 yellow corn tortillas small\r\n\r\n• 1 full slow cooker recipe Everything Beef\r\n\r\n• 1 cup red onions finely chopped\r\n\r\n• 1 cup cilantro finely chopped\r\n\r\n• 2 limes each cut into 4 wedges\r\n\r\n• 1 cup salsa verde\r\n\r\n• 1 jalapeño medium, stemmed, seeded, and chopped or sliced", Steps = "1) Place a few tortillas at a time in a single layer in a dry skillet or on a griddle over medium-high heat. Cook for 1 to 2 minutes on one side, flip, and repeat.\r\n\r\n2) Stack them so there are two on top of each other.\r\n\r\n3) Add an even amount of shredded meat to each tortilla.4) Top with onions and cilantro.\r\n\r\n5) Serve with lime wedges and salsa on the side.\r\n\r\n6) Squeeze lime on each taco right before eating. Spoon on salsa.", Bookmark = "No", Image = "taco.png" });
            //preloadedRecipe.Add(new PreloadedRecipe { Id = 13, RecipeName = "Carrot & Zucchini Whole Grain Muffins", Description = "Enjoy muffins without the guilt.", Time = "40 mins", Ingredients = "• 1 1/2 cups white whole-wheat flour\r\n\r\n• 2 tablespoons wheat germ\r\n\r\n• 1 teaspoon baking powder\r\n\r\n• 1/2 teaspoon baking soda\r\n\r\n• 1/4 teaspoon sea salt\r\n\r\n• 1 teaspoon cinnamon\r\n\r\n• 1 cup granola recipe for Granola\r\n\r\n• 1/3 cup coconut oil\r\n\r\n• 1/3 cup honey\r\n\r\n• 1 egg large, slightly whipped\r\n\r\n• 1 teaspoon vanilla\r\n\r\n• 1/2 cup zucchini with peeling, finely grated\r\n\r\n• 1/2 cup carrot peeled, finely grated\r\n\r\n• 1 cup buttermilk low-fat", Steps = "1) Preheat oven to 350 degrees.\r\nCombine streusel ingredients in a small bowl and set aside.r\n\r\n2) In a large mixing bowl, whisk together dry ingredients, set aside.r\n\r\n3) Add remaining ingredients to a medium mixing bowl, stir until combined.r\n\r\n4) Pour wet ingredients into dry and stir just until moist.r\n\r\n5) Line muffin tin with paper cup holders or mist with nonstick cooking spray.r\n\r\n6) Fill tins to 2/3 full, add approximately 1 teaspoon streusel to the top of each muffin.r\n\r\n7) Bake 15-17 minutes or until a toothpick inserted in the middle comes out clean and muffins are golden.", Bookmark = "No", Image = "taco.png" });
            //preloadedRecipe.Add(new PreloadedRecipe { Id = 14, RecipeName = "Thai Beef Salad", Description = "Enjoy a classic Thai food takeout order at home.", Time = "25 mins", Ingredients = "• 2 green onions chopped\r\n\r\n• 1 cup cilantro fresh, chopped\r\n\r\n• 1/2 cup mint leaves fresh, chopped\r\n\r\n• 1/4 cup basil fresh, chopped\r\n\r\n• 1 cup lime juice\r\n\r\n• 1/4 cup soy sauce low-sodium\r\n\r\n• 1/2 teaspoon red pepper flakes more or less to taste\r\n\r\n• 2 tablespoons honey\r\n\r\n• 1 pound lean flank steak\r\n\r\n• 1 tablespoon olive oil\r\n\r\n• 1 teaspoon kosher salt\r\n\r\n• 1/2 teaspoon ground black pepper\r\n\r\n• 3 cups romaine lettuce chopped\r\n\r\n• 2 cups baby arugula\r\n\r\n• 2 cups baby spinach\r\n\r\n• 1 cucumber medium, sliced into half moons\r\n\r\n• 1 cup grape tomatoes or cherry tomatoes, cut in 1/2 lengthwise", Steps = "1) In a large bowl, combine the green onion, cilantro, mint, basil, lime juice, soy sauce, red pepper flakes, and honey; stir well and set aside\r\n\r\n2) Preheat a grill to high heat.\r\n\r\n 3) Rub the flank steak with olive oil and season with salt and pepper.\r\n\r\n 4) Cook the steak to the desired doneness.\r\n\r\n 5) We recommend cooking the steak to medium, or about 5 minutes per side.\r\n\r\n 6) Remove the steak from the grill and let rest for 5 minutes.\r\n\r\n 7) While the steak is resting, combine the romaine, arugula, and spinach in a large bowl and toss well.\r\n\r\n 8) Divide between serving bowls.\r\n\r\n 9) Top the lettuce with the cucumber and tomatoes.\r\n\r\n 10) Slice the steak into strips and lay over the lettuce.\r\n\r\n 11) Drizzle the cilantro dressing over top", Bookmark = "No", Image = "thaisalad.png" });
            //preloadedRecipe.Add(new PreloadedRecipe { Id = 15, RecipeName = "Tofu Chocolate Mousse", Description = "Vegan and gluten free dessert.", Time = "2 hrs 20 min", Ingredients = "• 2 cups dark chocolate chips vegan\r\n\r\n• 14 ounces soft silken tofu\r\n\r\n• 1/3 cup almond milk\r\n\r\n• 2 tablespoons maple syrup\r\n\r\n• 2 teaspoons vanilla extract\r\n\r\n• 1 pinch kosher salt", Steps = "1) Melt chocolate in a double boiler under low heat.\r\n\r\n 2) Combine the melted chocolate with the tofu, almond milk, maple syrup, vanilla, and salt in a blender.\r\n\r\n 3) Blend all ingredients together. If it seems too thick, add almond milk, one tablespoon at a time. The texture should resemble pudding.\r\n\r\n 4) Make sure all components have blended well by scraping down the sides of the blender.\r\n\r\n 5) Pour mousse into a container and refrigerate for 2 hours.", Bookmark = "No", Image = "mousse.png" });

            //foreach (var recipe in preloadedRecipe)
            //{
            //    Database._database.InsertAsync(recipe);
            //}

            //navigate to main page
            MainPage = new MasterDetailPageYourFood();
        }
        
        protected override void OnStart()
        {
        }

        protected override void OnSleep()
        {
        }

        protected override void OnResume()
        {
        }
    }
}
